# Generated by Django 3.2.6 on 2021-11-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='selected_by',
            field=models.ManyToManyField(related_name='choose_doctor', to='portal.Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='choice',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
