# Generated by Django 3.2.6 on 2021-11-09 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0008_auto_20211109_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.doctor')),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reciever_pres', to='portal.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.doctor')),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='portal.patient')),
            ],
        ),
    ]
